
#   ███╗░░░███╗░█████╗░██████╗░░██████╗  ██████╗░██╗░░░░░██╗░░░██╗░██████╗
#   ████╗░████║██╔══██╗██╔══██╗██╔════╝  ██╔══██╗██║░░░░░██║░░░██║██╔════╝
#   ██╔████╔██║███████║██████╔╝╚█████╗░  ██████╔╝██║░░░░░██║░░░██║╚█████╗░
#   ██║╚██╔╝██║██╔══██║██╔═══╝░░╚═══██╗  ██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗
#   ██║░╚═╝░██║██║░░██║██║░░░░░██████╔╝  ██║░░░░░███████╗╚██████╔╝██████╔╝
#   ╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░░░░╚═════╝░  ╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░


#   ██████╗░██╗░░░██╗        █████╗░██╗░░░░░███╗░░░███╗░█████╗░███╗░░██╗░█████╗░██╗░░██╗██████╗░░░███╗░░
#   ██╔══██╗╚██╗░██╔╝        ██╔══██╗██║░░░░░████╗░████║██╔══██╗████╗░██║██╔══██╗╚██╗██╔╝╚════██╗░████║░░
#   ██████╦╝░╚████╔╝░        ███████║██║░░░░░██╔████╔██║███████║██╔██╗██║███████║░╚███╔╝░░░███╔═╝██╔██║░░
#   ██╔══██╗░░╚██╔╝░░        ██╔══██║██║░░░░░██║╚██╔╝██║██╔══██║██║╚████║██╔══██║░██╔██╗░██╔══╝░░╚═╝██║░░
#   ██████╦╝░░░██║░░░        ██║░░██║███████╗██║░╚═╝░██║██║░░██║██║░╚███║██║░░██║██╔╝╚██╗███████╗███████╗
#   ╚═════╝░░░░╚═╝░░░        ╚═╝░░╚═╝╚══════╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚══════╝


#
#   URL for the /logo command
#

#
#   Make sure the image is preferably 128 by 128 or server could lag
#

LOGO: 'https://discord.com/channels/946976330459807754/973439244691472504/973473390667108372'

